;=============================================================================
;jude
;=============================================================================
;
; Simple text-based GUI system and widget library.
;
; Copyright (c) 2022, 2025 Daniel England.
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU General Public License as published by
; the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; GNU General Public License for more details.
;
; You should have received a copy of the GNU General Public License
; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;
;=============================================================================

LABELCTRL__actvctrl_p: .equ 42

PAGEBTNCTRL__actvpage_p: .equ 42

EDITCTRL__textsz: .equ 42
EDITCTRL__textmaxsz: .equ 43

RADIOGRPCTRL__controls_p: .equ 42
RADIOGRPCTRL__controlscnt: .equ 46
RADIOGRPCTRL__labelctrl: .equ 47

RADIOBTNCTRL__groupctrl_p: .equ 42